// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr5r-E9GyfPVWK6idlK_L000cCMrgeJew',
    appId: '1:777669008164:web:c1847d370bb4e49b0671b1',
    messagingSenderId: '777669008164',
    projectId: 'hemlife-c6624',
    authDomain: 'hemlife-c6624.firebaseapp.com',
    storageBucket: 'hemlife-c6624.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3R4XbjVYremtN88hLX9aP0b64rreMgbw',
    appId: '1:777669008164:android:dcd9266e611790580671b1',
    messagingSenderId: '777669008164',
    projectId: 'hemlife-c6624',
    storageBucket: 'hemlife-c6624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4YLiEyImMKeLlp-EF9FnRDO6F5IsGlAY',
    appId: '1:777669008164:ios:e5783f582279b84f0671b1',
    messagingSenderId: '777669008164',
    projectId: 'hemlife-c6624',
    storageBucket: 'hemlife-c6624.appspot.com',
    iosBundleId: 'com.example.hemlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4YLiEyImMKeLlp-EF9FnRDO6F5IsGlAY',
    appId: '1:777669008164:ios:e5783f582279b84f0671b1',
    messagingSenderId: '777669008164',
    projectId: 'hemlife-c6624',
    storageBucket: 'hemlife-c6624.appspot.com',
    iosBundleId: 'com.example.hemlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr5r-E9GyfPVWK6idlK_L000cCMrgeJew',
    appId: '1:777669008164:web:f927f7554cffab8d0671b1',
    messagingSenderId: '777669008164',
    projectId: 'hemlife-c6624',
    authDomain: 'hemlife-c6624.firebaseapp.com',
    storageBucket: 'hemlife-c6624.appspot.com',
  );
}
